from selenium.webdriver.common.by import By

class LocatorsforOrder:
    ORDER_TAB = (By.XPATH, ".//button[text() = 'Заказать']")
    WHOSE_ORDER = (By.XPATH, ".//div[text() = 'Для кого самокат']")
    NAME = (By.XPATH, ".//input[@placeholder = '* Имя']")
    SURNAME = (By.XPATH, ".//input[@placeholder = '* Фамилия']")
    ADDRES = (By.XPATH, ".//input[@placeholder = '* Адрес: куда привезти заказ']")
    METRO = (By.XPATH, ".//input[@placeholder = '* Станция метро']")
    STATIONS = (By.XPATH, ".//div[contains(@class,'select-search has-focus')]")
    SELECT = (By.XPATH, ".//div[@class = 'select-search__select']")
    PHONE = (By.XPATH, ".//input[@placeholder = '* Телефон: на него позвонит курьер']")
    FURTHER_TAB = (By.XPATH, ".//button[text() = 'Далее']")
    BACK_TAB = (By.XPATH, ".//button[text() = 'Назад']")
    TIME = (By.XPATH, ".//input[@placeholder = '* Когда привезти самокат']")
    DAY = (By.XPATH, ".//div[contains(@class, 'today')]")
    RENTAL_PERIOD = (By.XPATH, ".//div[text() = '* Срок аренды']")
    LIST = (By.XPATH, ".//div[@class = 'Dropdown-root is-open']")
    DAY_SELECTION = (By.XPATH, ".//div[text() = 'сутки']")
    COLOR = (By.XPATH, ".//input[@id = 'black']")
    CHECKBOX = (By.XPATH, ".//div[@class = 'Order_Checkboxes__3lWSI Order_FilledContainer__2MKAk']")
    COMMENT = (By.XPATH, ".//input[@placeholder = 'Комментарий для курьера']")
    CLICK_ORGER = (By.XPATH, ".//button[@class = 'Button_Button__ra12g Button_Middle__1CSJM' and text() ='Заказать']")
    CLARIFICATION = (By.XPATH, ".//div[text() = 'Хотите оформить заказ?']")
    YES_TAB = (By.XPATH, ".//button[text() = 'Да']")
    SUCCESSFULLY_COMPLITED = (By.XPATH, ".//div[text() = 'Заказ оформлен']")
    STATUS = (By.XPATH, ".//button[text() = 'Посмотреть статус']")
